### PR TITLE
lib/rodauth/features/base.rb: add `throw_status` method that throws :rodauth_error without needing to set_field_error

### PR DESCRIPTION
**Pull request by jf**
as per https://github.com/jeremyevans/rodauth/discussions/412

### CODE REVIEW

**Comment by jeremyevans** [comment]
The method I said I would accept in https://github.com/jeremyevans/rodauth/discussions/412#discussioncomment-9182587 would just call `throw :rodauth_error`.  Something like:

```ruby
def throw_error
  throw :rodauth_error
end
```

You could then write your own `throw_status` method that calls this method.  I would not accept a `throw_status` method, because there is nothing internal to Rodauth that uses it, as I mentioned in https://github.com/jeremyevans/rodauth/discussions/412#discussioncomment-9110491.

**Comment by jf** [comment]
I see. Thanks for the clarification. I'll update the PR

**Comment by jf** [comment]
hm, just realized that there is a `throw_error` method already in `lib/rodauth/features/base.rb` that has 2 arguments (`field`, and `error`). I could call the new method `throw_rodauth_error`... but I'm not sure I like this name / approach. What do you think of making `field` and `error` optional for `throw_error` like so?

```
def throw_error(field=nil, error=nil)
  set_field_error(field, error) unless field.nil? and error.nil?
end
```

**Comment by jeremyevans** [comment]
I already made it clear in https://github.com/jeremyevans/rodauth/discussions/412#discussioncomment-9182587 that 
I don't want to make the `throw_error` arguments optional.  I would be OK adding `throw_rodauth_error` as a separate method.

**Comment by jf** [comment]
My apologies. In my mind we were talking about modifying `throw_error_status` (https://github.com/jeremyevans/rodauth/discussions/412#discussioncomment-9172187); I thought things might be different for `throw_error`.

I've updated the PR to add `throw_rodauth_error`.

**Comment by jeremyevans** [comment]
Squash merged at b44b441

**Pull request closed without merging**
