### PR TITLE
Added Gemfile

### PR DESCRIPTION
**Pull request by igor-alexandrov**
## Description
This pull request adds a Gemfile to the Rodauth project. By including a Gemfile, it becomes easier for users and contributors to manage and install the required dependencies when working locally with Rodauth.

## Changes
 * Added a Gemfile to the project root.
 * Update .gitignore

### CODE REVIEW

**Comment by janko** [comment]
Jeremy doesn't encourage use of Gemfile in libraries, see https://github.com/jeremyevans/sequel/issues/1809 😉

**Comment by igor-alexandrov** [comment]
I see... in this case maybe Contributing guide should be updated. By the way, before creating this PR, I checked that both Roda (https://github.com/jeremyevans/roda/blob/master/Gemfile) and Sequel (https://github.com/jeremyevans/sequel/blob/master/Gemfile) have Gemfile in the repo.

**Comment by janko** [comment]
Oh, somehow I missed that, and was sure I didn't see Gemfiles in other repos, but I guess it was just this one 👍🏻

**Comment by igor-alexandrov** [comment]
So you suggest using `gem install --development rodauth`? Maybe this should be added to contributing?

**Comment by jeremyevans** [comment]
I'll add that to the `Dependencies` section of the `README`.

**Pull request closed without merging**
